modLoader="javafml"
loaderVersion="[37,)"
updateJSONURL="https://tophatcat.dev/red-pandas/update.json"
issueTrackerURL="https://github.com/tophatcats-mods/red-pandas/issues"
displayURL="https://tophatcat.dev/red-pandas/"
license="GNU Lesser General Public License 2.1"
credits="KiriCattus"
authors="KiriCattus"
#logoFile=""

[[mods]]
modId="redpandas"
version="${file.jarVersion}"
displayName="Red Pandas"
description='''
A small mod with just Red Pandas coz why not they are so cute!
'''

[[dependencies.redpandas]]
   modId="forge"
   mandatory=true
   versionRange="[37,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.redpandas]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17,]"
   ordering="NONE"
   side="BOTH"
